---
# This is an example for newton
server:
  vm_name: 'wp_server'

mysql:
  db_name: '{{ site_name }}_db'
  mysql_user: 'wordpress'

wordpress:
  version: '4.9.4'
  site_name: 'wordpress'

ansible:
  verbosity: 'vvv'